CREATE TABLE "private-real-esate-manager_admin" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_admin_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(320) NOT NULL,
	"added_by_user_id" integer,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "private-real-esate-manager_admin_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_contract" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_contract_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"property_id" integer NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"storage_path" varchar(1024) NOT NULL,
	"file_name" varchar(256) NOT NULL,
	"size_bytes" integer,
	"notes" text,
	"uploaded_by_user_id" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_guest_access_code" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_guest_access_code_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"property_id" integer NOT NULL,
	"code" varchar(64) NOT NULL,
	"label" varchar(256),
	"is_enabled" boolean DEFAULT true NOT NULL,
	"expires_at" timestamp with time zone,
	"allowed_sections" jsonb DEFAULT '["property_details"]'::jsonb,
	"created_by_user_id" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "private-real-esate-manager_guest_access_code_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_invoice_attachment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_invoice_attachment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"invoice_id" integer NOT NULL,
	"storage_path" varchar(1024) NOT NULL,
	"file_name" varchar(256) NOT NULL,
	"mime_type" varchar(100),
	"size_bytes" integer,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_invoice_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_invoice_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(128) NOT NULL,
	"description" varchar(512),
	"icon" varchar(64),
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "private-real-esate-manager_invoice_category_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_invoice_line_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_invoice_line_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"invoice_id" integer NOT NULL,
	"category_id" integer NOT NULL,
	"total_bill_amount" numeric(10, 2) NOT NULL,
	"tenant_charge_amount" numeric(10, 2) NOT NULL,
	"proportion_type" varchar(32) DEFAULT 'fixed' NOT NULL,
	"proportion_value" numeric(5, 2),
	"description" text,
	"proof_storage_path" varchar(1024),
	"proof_file_name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_invoice" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_invoice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"property_id" integer NOT NULL,
	"billing_period_start" date NOT NULL,
	"billing_period_end" date NOT NULL,
	"label" varchar(256),
	"status" varchar(32) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"created_by_user_id" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"email_sent_at" timestamp with time zone,
	"email_sent_to" text
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_payment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_payment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"invoice_line_item_id" integer NOT NULL,
	"amount" numeric(10, 2) NOT NULL,
	"status" varchar(32) DEFAULT 'pending' NOT NULL,
	"paid_at" timestamp with time zone,
	"confirmed_at" timestamp with time zone,
	"confirmed_by_user_id" integer,
	"notes" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_property" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_property_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"address_line_1" varchar(512) NOT NULL,
	"address_line_2" varchar(512),
	"city" varchar(256) NOT NULL,
	"state" varchar(256),
	"postal_code" varchar(20),
	"country" varchar(100) DEFAULT 'AU' NOT NULL,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_property_image" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_property_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"property_id" integer NOT NULL,
	"storage_path" varchar(1024) NOT NULL,
	"file_name" varchar(256) NOT NULL,
	"mime_type" varchar(100),
	"size_bytes" integer,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_property_tenant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_property_tenant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"property_id" integer NOT NULL,
	"user_id" integer,
	"email" varchar(320) NOT NULL,
	"move_in_date" date,
	"move_out_date" date,
	"is_active" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supabase_user_id" uuid NOT NULL,
	"email" varchar(320) NOT NULL,
	"full_name" varchar(256),
	"avatar_url" varchar(1024),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "private-real-esate-manager_user_supabase_user_id_unique" UNIQUE("supabase_user_id"),
	CONSTRAINT "private-real-esate-manager_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_contract" ADD CONSTRAINT "private-real-esate-manager_contract_property_id_private-real-esate-manager_property_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."private-real-esate-manager_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_contract" ADD CONSTRAINT "private-real-esate-manager_contract_uploaded_by_user_id_private-real-esate-manager_user_id_fk" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "public"."private-real-esate-manager_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_guest_access_code" ADD CONSTRAINT "private-real-esate-manager_guest_access_code_property_id_private-real-esate-manager_property_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."private-real-esate-manager_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_guest_access_code" ADD CONSTRAINT "private-real-esate-manager_guest_access_code_created_by_user_id_private-real-esate-manager_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."private-real-esate-manager_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_invoice_attachment" ADD CONSTRAINT "private-real-esate-manager_invoice_attachment_invoice_id_private-real-esate-manager_invoice_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."private-real-esate-manager_invoice"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_invoice_line_item" ADD CONSTRAINT "private-real-esate-manager_invoice_line_item_invoice_id_private-real-esate-manager_invoice_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."private-real-esate-manager_invoice"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_invoice_line_item" ADD CONSTRAINT "private-real-esate-manager_invoice_line_item_category_id_private-real-esate-manager_invoice_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."private-real-esate-manager_invoice_category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_invoice" ADD CONSTRAINT "private-real-esate-manager_invoice_property_id_private-real-esate-manager_property_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."private-real-esate-manager_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_invoice" ADD CONSTRAINT "private-real-esate-manager_invoice_created_by_user_id_private-real-esate-manager_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."private-real-esate-manager_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_payment" ADD CONSTRAINT "private-real-esate-manager_payment_invoice_line_item_id_private-real-esate-manager_invoice_line_item_id_fk" FOREIGN KEY ("invoice_line_item_id") REFERENCES "public"."private-real-esate-manager_invoice_line_item"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_payment" ADD CONSTRAINT "private-real-esate-manager_payment_confirmed_by_user_id_private-real-esate-manager_user_id_fk" FOREIGN KEY ("confirmed_by_user_id") REFERENCES "public"."private-real-esate-manager_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_property_image" ADD CONSTRAINT "private-real-esate-manager_property_image_property_id_private-real-esate-manager_property_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."private-real-esate-manager_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_property_tenant" ADD CONSTRAINT "private-real-esate-manager_property_tenant_property_id_private-real-esate-manager_property_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."private-real-esate-manager_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_property_tenant" ADD CONSTRAINT "private-real-esate-manager_property_tenant_user_id_private-real-esate-manager_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."private-real-esate-manager_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "admin_email_idx" ON "private-real-esate-manager_admin" USING btree ("email");--> statement-breakpoint
CREATE INDEX "contract_property_idx" ON "private-real-esate-manager_contract" USING btree ("property_id");--> statement-breakpoint
CREATE UNIQUE INDEX "contract_property_version_idx" ON "private-real-esate-manager_contract" USING btree ("property_id","version");--> statement-breakpoint
CREATE UNIQUE INDEX "guest_code_idx" ON "private-real-esate-manager_guest_access_code" USING btree ("code");--> statement-breakpoint
CREATE INDEX "guest_property_idx" ON "private-real-esate-manager_guest_access_code" USING btree ("property_id");--> statement-breakpoint
CREATE INDEX "invoice_attachment_invoice_idx" ON "private-real-esate-manager_invoice_attachment" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "line_item_invoice_idx" ON "private-real-esate-manager_invoice_line_item" USING btree ("invoice_id");--> statement-breakpoint
CREATE UNIQUE INDEX "line_item_invoice_category_idx" ON "private-real-esate-manager_invoice_line_item" USING btree ("invoice_id","category_id");--> statement-breakpoint
CREATE INDEX "invoice_property_idx" ON "private-real-esate-manager_invoice" USING btree ("property_id");--> statement-breakpoint
CREATE INDEX "invoice_period_idx" ON "private-real-esate-manager_invoice" USING btree ("property_id","billing_period_start");--> statement-breakpoint
CREATE INDEX "payment_line_item_idx" ON "private-real-esate-manager_payment" USING btree ("invoice_line_item_id");--> statement-breakpoint
CREATE INDEX "property_image_property_idx" ON "private-real-esate-manager_property_image" USING btree ("property_id");--> statement-breakpoint
CREATE INDEX "property_tenant_property_idx" ON "private-real-esate-manager_property_tenant" USING btree ("property_id");--> statement-breakpoint
CREATE INDEX "property_tenant_user_idx" ON "private-real-esate-manager_property_tenant" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "property_tenant_unique_idx" ON "private-real-esate-manager_property_tenant" USING btree ("property_id","email");--> statement-breakpoint
CREATE UNIQUE INDEX "user_supabase_id_idx" ON "private-real-esate-manager_user" USING btree ("supabase_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "user_email_idx" ON "private-real-esate-manager_user" USING btree ("email");