CREATE TABLE "private-real-esate-manager_property_document" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_property_document_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"property_id" integer NOT NULL,
	"document_type" varchar(64) NOT NULL,
	"file_name" varchar(256) NOT NULL,
	"storage_path" varchar(1024) NOT NULL,
	"mime_type" varchar(100),
	"size_bytes" integer,
	"notes" text,
	"uploaded_by_user_id" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_property_document" ADD CONSTRAINT "private-real-esate-manager_property_document_property_id_private-real-esate-manager_property_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."private-real-esate-manager_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_property_document" ADD CONSTRAINT "private-real-esate-manager_property_document_uploaded_by_user_id_private-real-esate-manager_user_id_fk" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "public"."private-real-esate-manager_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "property_document_property_idx" ON "private-real-esate-manager_property_document" USING btree ("property_id");--> statement-breakpoint
CREATE INDEX "property_document_type_idx" ON "private-real-esate-manager_property_document" USING btree ("document_type");