CREATE TABLE "private-real-esate-manager_conversation_participant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_conversation_participant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conversation_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"joinedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_conversation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_conversation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_message_read_status" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_message_read_status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"message_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"readAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "private-real-esate-manager_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conversation_id" integer NOT NULL,
	"sender_id" integer NOT NULL,
	"content" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_conversation_participant" ADD CONSTRAINT "private-real-esate-manager_conversation_participant_conversation_id_private-real-esate-manager_conversation_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."private-real-esate-manager_conversation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_conversation_participant" ADD CONSTRAINT "private-real-esate-manager_conversation_participant_user_id_private-real-esate-manager_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."private-real-esate-manager_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_message_read_status" ADD CONSTRAINT "private-real-esate-manager_message_read_status_message_id_private-real-esate-manager_message_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."private-real-esate-manager_message"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_message_read_status" ADD CONSTRAINT "private-real-esate-manager_message_read_status_user_id_private-real-esate-manager_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."private-real-esate-manager_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_message" ADD CONSTRAINT "private-real-esate-manager_message_conversation_id_private-real-esate-manager_conversation_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."private-real-esate-manager_conversation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private-real-esate-manager_message" ADD CONSTRAINT "private-real-esate-manager_message_sender_id_private-real-esate-manager_user_id_fk" FOREIGN KEY ("sender_id") REFERENCES "public"."private-real-esate-manager_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "conversation_participant_unique_idx" ON "private-real-esate-manager_conversation_participant" USING btree ("conversation_id","user_id");--> statement-breakpoint
CREATE INDEX "conversation_participant_user_idx" ON "private-real-esate-manager_conversation_participant" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "message_read_status_unique_idx" ON "private-real-esate-manager_message_read_status" USING btree ("message_id","user_id");--> statement-breakpoint
CREATE INDEX "message_conversation_idx" ON "private-real-esate-manager_message" USING btree ("conversation_id");