CREATE TABLE "private-real-esate-manager_app_setting" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "private-real-esate-manager_app_setting_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" varchar(128) NOT NULL,
	"value" text DEFAULT '' NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "private-real-esate-manager_app_setting_key_unique" UNIQUE("key")
);
